version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - api-data:/app/apps/api/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:3000}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://localhost:3000}
    depends_on:
      - api
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  api-data:
